export const omanSchema = {
  yupSchema: {},
  initialValue: {
    personalDetails: {
      firstName: '',
      lastName: '',
      nationality: '',
      entryType: '',
      gender: '',
      passportNumber: '',
      passportColouredPhoto:'',
      profilePhoto:'',
    },
    generalDetails: {
      currentAddress: '',
      city: '',
      state: '',
      zipCode: '',
      phoneNumber: '',
      whatsappNumber: '',
      email: '',
      purposeOfVisit: '',
    },
    passportExpiryDate: '',
    dateOfBirth: '',
    arrivalDate: '',
    interested:'',
    termsAndConditions: false,
  },
};
